import { getSession } from 'next-auth/client';
import Head from 'next/head';
import Image from 'next/image';
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widget from "../components/Widget";

export default function Home({session}) {
  /* if(!session) return <Login /> */
  
  return (
    <div className="h-screen bg-gray-100 overflow-hidden" >
      <Head>
        <title>Baze App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className="flex   ">
        
        <Sidebar/>
        <Feed/>
        <Widget/>
      </main>
    </div>
  );
}
export  async function getServerSideProps(context) {
  // Get the user
  const session = await getSession(context);
  return{
    props:{
      session
    }
  }
}